/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import avengers.SistemaAsignacion;
import heroes.AcuaMan;
import heroes.Heroe;
import heroes.Hulk;
import heroes.IronMan;
import heroes.SpiderMan;
import heroes.SuperMan;
import heroes.Thor;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import misiones.Mision;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import notificaciones.TelegramNotifier;

/**
 *
 * @author mateo
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    
    private GestorDeMisiones gestorMision=new GestorDeMisiones(); 
    private GestorDeHeroes gestorHeroe = new GestorDeHeroes();
    private SistemaAsignacion asignacion = new SistemaAsignacion();
   /*
    Se crea los Jpanel y mas herramientas que ayudan al trabajo 
    */
    public InterfazPrincipal() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Principal = new javax.swing.JPanel();
        JP_ListaDeMisiones = new javax.swing.JPanel();
        JL_TituloDeMisiones = new javax.swing.JLabel();
        JL_NombreMision = new javax.swing.JLabel();
        JL_HabilidadMIsion = new javax.swing.JLabel();
        JC_ListaHabilidades = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        JT_MisionNombre = new javax.swing.JTextPane();
        JB_CrearMison = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        JT_TextoDeMisiones = new javax.swing.JTextArea();
        JP_Titulo = new javax.swing.JPanel();
        LA_Texto = new javax.swing.JLabel();
        JP_LIstadoHeroes = new javax.swing.JPanel();
        JC_ListadoHeroes = new javax.swing.JComboBox<>();
        JL_TituloHeroes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_TextoDeHeroes = new javax.swing.JTextArea();
        JL_NombreHeroe = new javax.swing.JLabel();
        JL_Tipo = new javax.swing.JLabel();
        JB_CrearHeroe = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_HeroeNombre = new javax.swing.JTextPane();
        JB_EjcutarMison = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JP_Principal.setBackground(new java.awt.Color(0, 102, 102));

        JP_ListaDeMisiones.setBackground(new java.awt.Color(102, 102, 102));

        JL_TituloDeMisiones.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JL_TituloDeMisiones.setForeground(new java.awt.Color(255, 255, 255));
        JL_TituloDeMisiones.setText("Crear Nuevas Misiones");

        JL_NombreMision.setBackground(new java.awt.Color(255, 255, 255));
        JL_NombreMision.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JL_NombreMision.setForeground(new java.awt.Color(255, 255, 255));
        JL_NombreMision.setText("Nombre");

        JL_HabilidadMIsion.setBackground(new java.awt.Color(255, 255, 255));
        JL_HabilidadMIsion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JL_HabilidadMIsion.setForeground(new java.awt.Color(255, 255, 255));
        JL_HabilidadMIsion.setText("Habiliad");

        JC_ListaHabilidades.setBackground(new java.awt.Color(153, 153, 153));
        JC_ListaHabilidades.setForeground(new java.awt.Color(255, 255, 255));
        JC_ListaHabilidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acuatica", "Control FUego", "Sigilo", "Trepar Muros", "Volar" }));
        JC_ListaHabilidades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JC_ListaHabilidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_ListaHabilidadesActionPerformed(evt);
            }
        });

        JT_MisionNombre.setBackground(new java.awt.Color(153, 153, 153));
        JT_MisionNombre.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        JT_MisionNombre.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(JT_MisionNombre);

        JB_CrearMison.setBackground(new java.awt.Color(153, 153, 153));
        JB_CrearMison.setForeground(new java.awt.Color(255, 255, 255));
        JB_CrearMison.setText("Crea Mision");
        JB_CrearMison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_CrearMisonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_CrearMisonMouseExited(evt);
            }
        });
        JB_CrearMison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearMisonActionPerformed(evt);
            }
        });

        JT_TextoDeMisiones.setBackground(new java.awt.Color(153, 153, 153));
        JT_TextoDeMisiones.setColumns(20);
        JT_TextoDeMisiones.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        JT_TextoDeMisiones.setForeground(new java.awt.Color(0, 102, 102));
        JT_TextoDeMisiones.setRows(5);
        jScrollPane5.setViewportView(JT_TextoDeMisiones);

        javax.swing.GroupLayout JP_ListaDeMisionesLayout = new javax.swing.GroupLayout(JP_ListaDeMisiones);
        JP_ListaDeMisiones.setLayout(JP_ListaDeMisionesLayout);
        JP_ListaDeMisionesLayout.setHorizontalGroup(
            JP_ListaDeMisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ListaDeMisionesLayout.createSequentialGroup()
                .addGroup(JP_ListaDeMisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JP_ListaDeMisionesLayout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_ListaDeMisionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JL_TituloDeMisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_ListaDeMisionesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(JP_ListaDeMisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_ListaDeMisionesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(JL_HabilidadMIsion))
                            .addComponent(JL_NombreMision))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP_ListaDeMisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(JC_ListaHabilidades, 0, 181, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ListaDeMisionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JB_CrearMison, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        JP_ListaDeMisionesLayout.setVerticalGroup(
            JP_ListaDeMisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_ListaDeMisionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_TituloDeMisiones)
                .addGap(10, 10, 10)
                .addGroup(JP_ListaDeMisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_NombreMision)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_ListaDeMisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JC_ListaHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_HabilidadMIsion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(JB_CrearMison, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JP_Titulo.setBackground(new java.awt.Color(102, 102, 102));

        LA_Texto.setBackground(new java.awt.Color(255, 255, 255));
        LA_Texto.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        LA_Texto.setForeground(new java.awt.Color(255, 255, 255));
        LA_Texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA_Texto.setText("GESTOR DE MISIONES");

        javax.swing.GroupLayout JP_TituloLayout = new javax.swing.GroupLayout(JP_Titulo);
        JP_Titulo.setLayout(JP_TituloLayout);
        JP_TituloLayout.setHorizontalGroup(
            JP_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_TituloLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(LA_Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        JP_TituloLayout.setVerticalGroup(
            JP_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LA_Texto, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        JP_LIstadoHeroes.setBackground(new java.awt.Color(102, 102, 102));

        JC_ListadoHeroes.setBackground(new java.awt.Color(153, 153, 153));
        JC_ListadoHeroes.setForeground(new java.awt.Color(255, 255, 255));
        JC_ListadoHeroes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AcuaMan", "Hulk", "IronMan", "SpiderMan", "Superman", "Thor" }));
        JC_ListadoHeroes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC_ListadoHeroesActionPerformed(evt);
            }
        });

        JL_TituloHeroes.setBackground(new java.awt.Color(255, 255, 255));
        JL_TituloHeroes.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JL_TituloHeroes.setForeground(new java.awt.Color(255, 255, 255));
        JL_TituloHeroes.setText("Crear Nuevos Heroes");

        JT_TextoDeHeroes.setBackground(new java.awt.Color(153, 153, 153));
        JT_TextoDeHeroes.setColumns(20);
        JT_TextoDeHeroes.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        JT_TextoDeHeroes.setForeground(new java.awt.Color(0, 102, 102));
        JT_TextoDeHeroes.setRows(5);
        jScrollPane1.setViewportView(JT_TextoDeHeroes);

        JL_NombreHeroe.setBackground(new java.awt.Color(255, 255, 255));
        JL_NombreHeroe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JL_NombreHeroe.setForeground(new java.awt.Color(255, 255, 255));
        JL_NombreHeroe.setText("Nombre");

        JL_Tipo.setBackground(new java.awt.Color(255, 255, 255));
        JL_Tipo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JL_Tipo.setForeground(new java.awt.Color(255, 255, 255));
        JL_Tipo.setText("Tipo");

        JB_CrearHeroe.setBackground(new java.awt.Color(153, 153, 153));
        JB_CrearHeroe.setForeground(new java.awt.Color(255, 255, 255));
        JB_CrearHeroe.setText("Crea Heroe");
        JB_CrearHeroe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_CrearHeroeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_CrearHeroeMouseExited(evt);
            }
        });
        JB_CrearHeroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearHeroeActionPerformed(evt);
            }
        });

        JT_HeroeNombre.setBackground(new java.awt.Color(153, 153, 153));
        JT_HeroeNombre.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        JT_HeroeNombre.setForeground(new java.awt.Color(255, 255, 255));
        JT_HeroeNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(JT_HeroeNombre);

        javax.swing.GroupLayout JP_LIstadoHeroesLayout = new javax.swing.GroupLayout(JP_LIstadoHeroes);
        JP_LIstadoHeroes.setLayout(JP_LIstadoHeroesLayout);
        JP_LIstadoHeroesLayout.setHorizontalGroup(
            JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_LIstadoHeroesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_Tipo)
                    .addComponent(JB_CrearHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JP_LIstadoHeroesLayout.createSequentialGroup()
                .addGroup(JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JP_LIstadoHeroesLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(JL_TituloHeroes, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JP_LIstadoHeroesLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(JL_NombreHeroe)
                            .addGap(50, 50, 50)
                            .addGroup(JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JC_ListadoHeroes, 0, 182, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        JP_LIstadoHeroesLayout.setVerticalGroup(
            JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_LIstadoHeroesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_TituloHeroes)
                .addGroup(JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_LIstadoHeroesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_NombreHeroe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JP_LIstadoHeroesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_LIstadoHeroesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(JC_ListadoHeroes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(JB_CrearHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        JB_EjcutarMison.setBackground(new java.awt.Color(153, 153, 153));
        JB_EjcutarMison.setForeground(new java.awt.Color(255, 255, 255));
        JB_EjcutarMison.setText("COMENZAR MISION");
        JB_EjcutarMison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_EjcutarMisonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_EjcutarMisonMouseExited(evt);
            }
        });
        JB_EjcutarMison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EjcutarMisonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_PrincipalLayout = new javax.swing.GroupLayout(JP_Principal);
        JP_Principal.setLayout(JP_PrincipalLayout);
        JP_PrincipalLayout.setHorizontalGroup(
            JP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_PrincipalLayout.createSequentialGroup()
                .addGroup(JP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_PrincipalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(JP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_EjcutarMison, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JP_PrincipalLayout.createSequentialGroup()
                                .addComponent(JP_LIstadoHeroes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JP_ListaDeMisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JP_PrincipalLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(JP_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        JP_PrincipalLayout.setVerticalGroup(
            JP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_PrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JP_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JP_LIstadoHeroes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_ListaDeMisiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_EjcutarMison, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JC_ListadoHeroesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_ListadoHeroesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JC_ListadoHeroesActionPerformed


    /**
     * Evento que se ejecuta al presionar el botón para crear un nuevo héroe.
     * <p>
     * Este método obtiene el nombre ingresado en el campo de texto y valida
     * que no esté vacío ni repetido. Si las validaciones son correctas,
     * se obtiene el tipo de héroe seleccionado en el {@code JComboBox}
     * y se crea un nuevo héroe mediante el {@code GestorDeHeroes}.
     * </p>
     * <p>
     * Finalmente, se actualiza el área de texto mostrando la lista
     * de héroes registrados en el sistema.
     * </p>
     *
     * @param evt evento generado al hacer clic en el botón
     */
    private void JB_CrearHeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearHeroeActionPerformed
         
        // Obtener texto del JTextField
        String nombreNew = JT_HeroeNombre.getText();

        //se comprueb si no esta vacio el JT
        if(!gestorHeroe.ValidarTexto(nombreNew)){
        JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
        
        //se comprueb si no esta repetido el nombre
        }else if(gestorHeroe.nombreRepetido(nombreNew)){
        JOptionPane.showMessageDialog(this, "NO se puede erepetir el nombre");
        }
        else{
            // Obtener héroe seleccionado
            String tipoHeroe = JC_ListadoHeroes.getSelectedItem().toString();
            
            //crea heroe
            this.gestorHeroe.crearNuevoHeroe(tipoHeroe, nombreNew);
        
        }

        StringBuilder texto = gestorHeroe.imprimirTexto();
        // Mostrar el resultado en el JTextArea
        JT_TextoDeHeroes.setText(texto.toString());
    }//GEN-LAST:event_JB_CrearHeroeActionPerformed

    private void JC_ListaHabilidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC_ListaHabilidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JC_ListaHabilidadesActionPerformed

    private void JB_CrearMisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearMisonActionPerformed
        // TODO add your handling code here:
        String MisionNew=JT_MisionNombre.getText();
        
        if(!gestorMision.ValidarTexto(MisionNew)){
        JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para la mision");
        }
        else if(gestorMision.nombreRepetido(MisionNew)){
        JOptionPane.showMessageDialog(this, "NO se puede crear la misma mision nuevamente");
        }
        else{
            String tipoHabuilidad =JC_ListaHabilidades.getSelectedItem().toString();
            
            this.gestorMision.crearNuevaMision(MisionNew, tipoHabuilidad);
        }
        
        StringBuilder texto=gestorMision.imprimirMisiones();
        JT_TextoDeMisiones.setText(texto.toString());
    }//GEN-LAST:event_JB_CrearMisonActionPerformed

    /**
     * Evento que se ejecuta al presionar el botón de ejecutar misión.
     * <p>
     * Este método obtiene la lista de misiones y héroes registrados,
     * y utiliza el sistema de asignación para determinar qué héroe
     * puede realizar cada misión.
     * </p>
     * <p>
     * El resultado de la asignación se envía como notificación a
     * través de {@code TelegramNotifier} y también se muestra
     * en una ventana emergente mediante {@code JOptionPane}.
     * </p>
     *
     * @param evt evento generado al hacer clic en el botón
     */
    private void JB_EjcutarMisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EjcutarMisonActionPerformed

        String mesaje = this.asignacion.asignarMisionInterfaz(gestorMision.getMisiones(), gestorHeroe.getHeroes());
        
        TelegramNotifier notifier = new TelegramNotifier();
        // Mensaje simple
        notifier.enviarMensaje("\n----- RESULTADO DE EJECUCIÓN -----\n" + mesaje);
        JOptionPane.showMessageDialog(this, "\n----- RESULTADO DE EJECUCIÓN -----\n" + mesaje);
        
    }//GEN-LAST:event_JB_EjcutarMisonActionPerformed

    private void JB_CrearHeroeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CrearHeroeMouseEntered
        // Cambiar color del botón cuando el mouse está encima
        JB_CrearHeroe.setBackground(new Color(255,255,255));
        JB_CrearHeroe.setForeground(Color.GRAY);
    }//GEN-LAST:event_JB_CrearHeroeMouseEntered

    private void JB_CrearHeroeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CrearHeroeMouseExited
        
        // Regresar al color original
        JB_CrearHeroe.setBackground(new Color(153,153,153));
        JB_CrearHeroe.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JB_CrearHeroeMouseExited

    private void JB_CrearMisonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CrearMisonMouseEntered
        // Cambiar color del botón cuando el mouse está encima
        JB_CrearMison.setBackground(new Color(255,255,255));
        JB_CrearMison.setForeground(Color.GRAY);
    }//GEN-LAST:event_JB_CrearMisonMouseEntered

    private void JB_CrearMisonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CrearMisonMouseExited
        // Regresar al color original
        JB_CrearMison.setBackground(new Color(153,153,153));
        JB_CrearMison.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JB_CrearMisonMouseExited

    private void JB_EjcutarMisonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EjcutarMisonMouseEntered
        
        // Cambiar color del botón cuando el mouse está encima
        JB_EjcutarMison.setBackground(new Color(255,255,255));
        JB_EjcutarMison.setForeground(Color.GRAY);
    }//GEN-LAST:event_JB_EjcutarMisonMouseEntered

    private void JB_EjcutarMisonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EjcutarMisonMouseExited
        // Regresar al color original
        JB_EjcutarMison.setBackground(new Color(153,153,153));
        JB_EjcutarMison.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JB_EjcutarMisonMouseExited

    //////////////coidgo
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CrearHeroe;
    private javax.swing.JButton JB_CrearMison;
    private javax.swing.JButton JB_EjcutarMison;
    private javax.swing.JComboBox<String> JC_ListaHabilidades;
    private javax.swing.JComboBox<String> JC_ListadoHeroes;
    private javax.swing.JLabel JL_HabilidadMIsion;
    private javax.swing.JLabel JL_NombreHeroe;
    private javax.swing.JLabel JL_NombreMision;
    private javax.swing.JLabel JL_Tipo;
    private javax.swing.JLabel JL_TituloDeMisiones;
    private javax.swing.JLabel JL_TituloHeroes;
    private javax.swing.JPanel JP_LIstadoHeroes;
    private javax.swing.JPanel JP_ListaDeMisiones;
    private javax.swing.JPanel JP_Principal;
    private javax.swing.JPanel JP_Titulo;
    private javax.swing.JTextPane JT_HeroeNombre;
    private javax.swing.JTextPane JT_MisionNombre;
    private javax.swing.JTextArea JT_TextoDeHeroes;
    private javax.swing.JTextArea JT_TextoDeMisiones;
    private javax.swing.JLabel LA_Texto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
